// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowBackend.Data;

#nullable disable

namespace WorkflowBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227223207_AddPendingChanges")]
    partial class AddPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowBackend.Models.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("WorkflowBackend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("WorkflowBackend.Models.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApproverGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("approver_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Files")
                        .HasColumnType("text")
                        .HasColumnName("files");

                    b.Property<string>("FormSchema")
                        .HasColumnType("text")
                        .HasColumnName("form_schema");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ApproverGroupId");

                    b.HasIndex("CreatorId");

                    b.ToTable("templates");
                });

            modelBuilder.Entity("WorkflowBackend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WorkflowBackend.Models.Workflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApproverGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("approver_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Files")
                        .HasColumnType("text")
                        .HasColumnName("files");

                    b.Property<string>("FormData")
                        .HasColumnType("text")
                        .HasColumnName("form_data");

                    b.Property<string>("ReviewerStatuses")
                        .HasColumnType("text")
                        .HasColumnName("reviewer_statuses");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<string>("Timeline")
                        .HasColumnType("text")
                        .HasColumnName("timeline");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApproverGroupId");

                    b.HasIndex("CreatorId");

                    b.ToTable("workflows");
                });

            modelBuilder.Entity("template_reviewers", b =>
                {
                    b.Property<long>("group_id")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<long>("template_id")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("group_id", "template_id");

                    b.HasIndex("template_id");

                    b.ToTable("template_reviewers", (string)null);
                });

            modelBuilder.Entity("user_groups", b =>
                {
                    b.Property<long>("group_id")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("group_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<int>("role_id")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("role_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("workflow_reviewers", b =>
                {
                    b.Property<long>("group_id")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<long>("workflow_id")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("group_id", "workflow_id");

                    b.HasIndex("workflow_id");

                    b.ToTable("workflow_reviewers", (string)null);
                });

            modelBuilder.Entity("WorkflowBackend.Models.Template", b =>
                {
                    b.HasOne("WorkflowBackend.Models.Group", "ApproverGroup")
                        .WithMany()
                        .HasForeignKey("ApproverGroupId");

                    b.HasOne("WorkflowBackend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("ApproverGroup");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WorkflowBackend.Models.Workflow", b =>
                {
                    b.HasOne("WorkflowBackend.Models.Group", "ApproverGroup")
                        .WithMany()
                        .HasForeignKey("ApproverGroupId");

                    b.HasOne("WorkflowBackend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("ApproverGroup");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("template_reviewers", b =>
                {
                    b.HasOne("WorkflowBackend.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowBackend.Models.Template", null)
                        .WithMany()
                        .HasForeignKey("template_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("user_groups", b =>
                {
                    b.HasOne("WorkflowBackend.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowBackend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("WorkflowBackend.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowBackend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("workflow_reviewers", b =>
                {
                    b.HasOne("WorkflowBackend.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowBackend.Models.Workflow", null)
                        .WithMany()
                        .HasForeignKey("workflow_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
